### ISSUE TITLE
[BUG] TLS cert error on https://librepatron.com/

### ISSUE THREAD

**Issue by JeremyRand** [JeffVandrewJr/patron#13]
**Describe the bug**
The TLS cert for https://librepatron.com/ is invalid.

**To Reproduce**
1. Visit https://librepatron.com/ in Tor Browser 8.5.5.

**Expected behavior**
The website should load without errors.

**Observed behavior**

> librepatron.com uses an invalid security certificate. The certificate is only valid for the following names: shortener.secureserver.net, www.shortener.secureserver.net Error code: SSL_ERROR_BAD_CERT_DOMAIN

**Additional context**
I've tried switching Tor circuits, so I'm pretty sure this isn't an exit relay issue.

**Comment by JeffVandrewJr** [comment]
Thanks! That was an old demo site that has been taken down.

**Comment by JeremyRand** [comment]
I'm not sure why this issue was closed, given that the link in question is still present in the repo metadata.
