### ISSUE TITLE
Raspberry Pi 4 support

### ISSUE THREAD

**Issue by drptbl** [JeffVandrewJr/patron#15]
**Describe the feature**
Patron doesn't work on Raspberry Pi 4 (Raspbian Buster full 2019-09-26). Docker images (`isso` and `librepatron`) are reporting this error after everything seems to be started successfully:
```
standard_init_linux.go:211: exec user process caused "exec format error"
```
_hint: missing builds for raspberry architecture?_ - https://gitlab.com/gitlab-org/omnibus-gitlab/issues/4558)

**To Reproduce**
1. Start patron on Raspberry Pi 4 which is already hosting BTCPayServer.

**Additional context**
BTCPayServer works without issues but there are no benefits from patron (can't configure it, getting redirected to home page).

**Comment by JeffVandrewJr** [comment]
As mentioned in the documentation, LibrePatron is x64 only.

**Comment by JeremyRand** [comment]
Not clear to me why this was closed.  Is this a WONTFIX response, or would a PR be accepted that fixes the issue?

**Comment by JeffVandrewJr** [comment]
LibrePatron had little interest and is therefore no longer under active development.
