### ISSUE TITLE
Bitcoin Subscription and recurring Payments by LibrePatron?

### ISSUE THREAD

**Issue by onleines** [JeffVandrewJr/patron#16]
Hello, Jeff,

I am currently working on the different tools that run with BTCPay. 
I was very interested in your LibrePatron application and I was wondering if it is also suitable for recurring payments.

Currently I am running version 0.7.37, because an upgrade to 0.7.39 via maintenance of the BTCPay server (v1.0.4.2) did not work.

I hope that even with 0.7.37 the essential functions will still work. 

Can LibrePatron be used for recurring payments via Bitcoin and Lightning? No credit card, so no Square either. Only Bitcoin!

I believe that recurring payments are very suitable, as a donation for artists, website, YouTube channel or as a membership for a blog or service.

Unfortunately I did not find a live application of LibrePatron and probably could not see all features with my installation.
 
Thanks to your description I have set up a demo application at https://blog.btcpayserver.org/librepatron-patreon-alternative/.

The first payment I was able to make via https://patron.coincharge.io/support
 successfully. But what about recurring payments? What happens in the following months?

Is the cycle of a payment always 30 days? Always the first of a month or always 30 days after the first payment?

Does LibrePatron create a payment request on the BTCPay server, which is then automatically sent to the subscriber every month?
 
Is the payment request embedded in this email and is the link to the BTCPay payment page?

Can I see the paid invoices at BTCPay under Invoices or is this displayed at LibrePatron?

Does LibrePatron work as I have described it? Where can I make the necessary settings?

Can I also use Euro as currency or is it only possible to use USD?
Can I only use whole amounts, like 10 USD or is 9.99 EUR possible?

Thank you, if you can answer my questions. Or maybe you have lost interest in LibrePatron and want to dedicate yourself to other tasks. 
By the way, librepatron.com is no longer available ;-)

Thanks for assistance and best greetings from Germany
Jens

**Comment by JeffVandrewJr** [comment]
A cycle is always 30 days, and the currency is always USD. Every 30 days the customer is automatically emailed a new invoice. If they don't pay, their access is cut off.

Unfortunately there hasn't been much interest in the project, and my day job has become very busy, so I've only been doing security updates rather than adding new features.
