### ISSUE TITLE
Run without Docker

### ISSUE THREAD

**Issue by Sjors** [JeffVandrewJr/patron#4]
For old school folks, it's nice to have instructions and systemd scripts to run on e.g. Ubuntu. I already got most of it running.

**Comment by JeffVandrewJr** [comment]
While I appreciate the idea, from helping with support on the main BTCPay project, I've personally noticed that 90% of support requests come from the 1% of users who don't want to use Docker, so to best conserve resources I'm avoiding any "official" support for non-Docker installs. Those that wish to hack away on non-Docker installs are welcome to try!

**Comment by Sjors** [comment]
I can see the argument from support load, but in the long run it doesn't seem like a good idea to rely on Docker to keep everything isolated. It's strictly worse and more difficult to reason about than the protections already built into Linux. Code is more difficult to review, because it pulls in containers from various places.

Docker is easier to use, which explains most of the support load difference, but there is also the chicken-egg problem from lack of instructions and tooling to run without Docker.

**Comment by Sjors** [comment]
I created a very rough guide based on my own setup: https://gist.github.com/Sjors/beddd154fd9945264137b2b9db899af3

Not very practical at this point though.
