### ISSUE TITLE
Database backup procedure

### ISSUE THREAD

**Issue by Sjors** [JeffVandrewJr/patron#5]
I wrote a bunch of text for my own instance and then I was very stupid and did `docker-compose down -v`. That wiped the volume containing the database. I think we should recommend users to create a directory for the database and link the volume to that. The user can then make backups of that directory. I don't know how this interacts with BTCPay server magic.

**Comment by JeffVandrewJr** [comment]
Backup bis already accomplished in BTCPay-Docker. See https://github.com/btcpayserver/btcpayserver-docker/pull/117

**Comment by Sjors** [comment]
Good to know BTCPay handles the backups in the Docker setup. In that case backup instructions should be part of any (future) non-docker setup (#4).
